// app路径选择
export const NATIVE_PATH_TYPE = [
  { value: 'limited', name: '限时抢购' },
  { value: 'explode', name: '爆品福利' },
  { value: 'recommend', name: '特惠推荐' },
  { value: 'beanPrefecture', name: '卡豆专区' },
  // { value: 'phoneRecharge', name: '话费充值' },
  // { value: 'memberRecharge', name: '会员充值' },
  { value: 'blindBoxActivity', name: '天天抽奖' },
  { value: 'perimeterShops', name: '周边好店' },
  // { value: 'recommend', name: '小豆精选' },
  // { value: 'recommend', name: '今日上新' },
  // { value: 'billVoucherCouponPackage', name: '话费抵扣券包' },
  // { value: 'recommend', name: '平台通用券包' },
  // { value: 'recommend', name: '电商品券包' },
  { value: 'aroundTravel', name: '周边游玩' },
  { value: 'beanDistrictCommerce', name: '精选好物' },
  { value: 'dailyTaskPage', name: '赚豆任务' },
  { value: 'groupBuy', name: 'app-拼团' },
  { value: 'beanWeeklyCard', name: 'app-周卡' },
  { value: 'studyCenter', name: 'app-哒人学院' },
  { value: 'shoppingCircle', name: 'app-附近商圈' },
  { value: 'highCommission', name: 'app-高佣专区' },
  { value: 'dailyTaskInviteFriend', name: 'app-分享赚豆（邀请）' },
  { value: 'enterGroup', name: '小程序-加入社群页面' },
  { value: 'preChildTure', name: '小程序-吃喝玩乐购' },
  { value: 'userParticipation', name: '用户参团' },
  // { value: 'shareUser', name: '小程序-活动助力页面' },
];
