export const rightsJson = [
  {
    title: '身份铭牌',
    icon: 'https://resource-new.dakale.net/common/level/shenfenmingpai.png',
    name: 'nameplate',
    value: null,
  },
  {
    title: '商家任务',
    icon: 'https://resource-new.dakale.net/common/level/shangjiarenwu.png',
    name: 'promote',
    value: null,
  },
  {
    title: '哒人创作',
    icon: 'https://resource-new.dakale.net/common/level/darenchuangzuo.png',
    name: 'creation',
    value: null,
  },
  {
    title: '品宣任务',
    icon: 'https://resource-new.dakale.net/common/level/pinxuanrenwu.png',
    name: 'productAnnouncement',
    value: null,
  },
  {
    title: 'ip表情包',
    icon: 'https://resource-new.dakale.net/common/level/ipbiaoqing.png',
    name: 'emoticons',
    value: null,
  },
  {
    title: '排名优先',
    icon: 'https://resource-new.dakale.net/common/level/paimingyouxian.png',
    name: 'videoFirst',
    value: 2,
  },
  {
    title: '专属水印',
    icon: 'https://resource-new.dakale.net/common/level/zhuanshushuiyin.png',
    name: 'watermark',
    value: null,
  },
  {
    title: '哒人直播',
    icon: 'https://resource-new.dakale.net/common/level/darenzhibo.png',
    name: 'liveBroadcast',
    value: null,
  },
  {
    title: '哒人@',
    icon: 'https://resource-new.dakale.net/common/level/darenat.png',
    name: 'interconnected',
    value: null,
  },
  {
    title: '带货收益',
    icon: 'https://resource-new.dakale.net/common/level/daihuoshouyi.png',
    name: 'priceDifference',
    value: 50,
  },
  {
    title: '哒人打赏',
    icon: 'https://resource-new.dakale.net/common/level/darendashang.png',
    name: 'beanReward',
    value: null,
  },
  {
    title: '卡豆补贴',
    icon: 'https://resource-new.dakale.net/common/level/kadoubutie.png',
    name: 'platformBeanReward',
    value: 500,
  },
  {
    title: '专题活动',
    icon: 'https://resource-new.dakale.net/common/level/zhuantihuodong.png',
    name: 'specialEvent',
    value: null,
  },
  {
    title: '升级礼包',
    icon: 'https://resource-new.dakale.net/common/level/shengjilibao.png',
    name: 'exclusiveCoupon',
    value: {
      startMoney: 78,
      endMoney: 100,
      startCount: 5,
      endCount: 8,
    },
  },
  {
    title: '限时任务',
    icon: 'https://resource-new.dakale.net/common/level/xianshirenwu.png',
    name: 'limitedTimeReward',
    value: null,
  },
  {
    title: '广告任务',
    icon: 'https://resource-new.dakale.net/common/level/guanggaorenwu.png',
    name: 'advertising',
    value: null,
  },
];
