// 权限按钮映射 和 HandleSetTable 对应
export const ROLE_BUTTON_TYPE = {
  again: '重新发布',
  action: '使用规则',
  activate: '激活',
  actionDel: '删除行为',
  actionEdit: '修改行为',
  actionSave: '新增使用规则',
  againUp: '再次上架',
  addRemain: '增加库存',
  authEdit: '权限设置',
  assistanceInfo: '助力详情',
  addTags: '新增标签',
  addnum: '增加数量',
  award: '奖励',
  advert: '广告',
  adVideo_edit: '视频广告编辑',
  activeTemplate: '活动模板',

  BDSet: '关联BD',
  batchEdit: '批量修改',
  baseTrade: '基础设施',
  bussinessStatus: '营业状态',
  batchRouting: '批量分账',
  bannerEdit: 'banner编辑',
  bannerUpVersion: 'banner修改版本',
  bannerAddVersion: 'banner新增版本',
  bannerDown: 'banner下架',
  bannerUp: 'banner上架',
  bannerDel: 'banner删除',
  bannerAdd: 'banner新增',
  bannerAddPlace: 'banner新增位置',
  blindEdit: '盲盒编辑',
  blindDel: '盲盒新增',
  blindAdd: '盲盒新增',
  blindConfigEdit: '盲盒规则编辑',
  brand: '品牌',

  copy: '复制',
  check: '审核',
  close: '关闭',
  config: '配置',
  copyLink: '复制链接',
  couponAdd: '优惠券新增',
  cancelTemp: '取消实习',
  checkDetail: '审核记录',
  couponDetail: '优惠券详情',
  cancleRecommend: '取消推荐',
  connectedGoods: '关联商品',
  enrollGoods: '报名商品',
  configCondit: '条件配置',
  commerceSet: '带货设置',
  changeRemain: '调整库存',

  del: '删除',
  down: '下架',
  diary: '日志',
  direct: '平台直充',
  directDel: '删除平台直充',
  directEnd: '结束平台直充',
  directInfo: '平台直充任务详情',
  directSave: '直充卡豆充值',
  directDetail: '平台直充补贴详情',
  destoryDetail: '核销明细',
  download: '下载',

  eye: '查看',
  end: '结束',
  edit: '编辑',
  exportList: '导出',
  equityCoupon: '权益券',
  equityGoods: '权益商品',
  equityDummy: '虚拟权益',
  equityCommerceGoods: '电商商品',

  floatEdit: '浮窗编辑',
  floatEditVersion: '浮窗版本编辑',
  floatAddVersion: '浮窗版本新增',
  floatAddCity: '浮窗-新增城市',
  floatDel: '浮窗删除',
  floatDown: '浮窗下架',
  floatAdd: '浮窗新增',

  goodsCode: '商品码',
  givePrize: '赠送',
  getRecord: '领取记录',
  goodsDeliver: '发货',
  goodsView: '查看物流',
  globalPopEdit: '全局弹框编辑',
  globalUpVersion: '全局弹框修改版本',
  globalAddVersion: '全局弹框新增版本',
  globalPopAdd: '全局弹框新增',
  globalPopDel: '全局弹框删除',
  globalPopDown: '全局弹框下架',
  globalAddCity: '全局弹框新增城市',
  groupGoodsConfigAdd: '拼团商品配置新增',
  groupGoodsConfigDel: '拼团商品配置删除',

  handle: '处理',
  handleDeatil: '操作记录',
  holidaySave: '节日配置-新增',
  holidayDown: '节日配置-下架',
  holidayEdit: '节日配置-编辑',
  holidayInfo: '节日配置-详情',

  info: '详情',
  income: '收益明细',
  isWechat: '小程序展示控制',
  immediateGroup: '立即成团',
  iconEdit: '底部icon-编辑',
  iconVersionEdit: '底部icon-编辑版本',
  iconVersionDel: '底部icon-删除版本',
  iconVersionSave: '底部icon-新增版本',

  jobClass: '职位类别',

  mreOs: '商家端',
  markImg: '打卡图片',
  markText: '打卡文案',
  markTextAdd: '新增分享文案',
  markImgEdit: '修改打卡图片',
  markTextEdit: '修改打卡文案',
  merchantVideo_edit: '商家视频编辑',
  materialConfigDownLoad: '物料配置下载',
  materialConfigAdd: '物料配置新增',

  noticeAdd: '公告新增',
  noticeEdit: '公告修改',
  noticeDel: '公告删除',
  noticeSend: '公告发送',
  newWelfareEdit: '新人福利弹框编辑',
  newWelfareAdd: '新人福利弹框新增',
  newWinDel: '新手必中奖池删除',
  newWinAdd: '新手必中奖池新增',

  openAd: '开屏广告',
  orderDetail: '订单明细',

  push: '推送',
  puzzleAd: '拼图广告',
  placement: '置顶',
  peasDetail: '卡豆明细',
  preview: '预览',
  portraitEdit: '编辑画像',
  point: '点位',

  qrCode: '获取二维码',

  rate: '费率',
  role: '角色',
  revoke: '撤销',
  replay: '回复',
  relieve: '解约',
  roleAdd: '角色添加',
  roleEdit: '角色权限设置',
  rightsSet: '权益设置',
  roleStatus: '角色状态',
  recycleBean: '卡豆回收',
  reportCenter: '举报中心',
  recommendList: '团队',
  rechargeDetail: '充值记录',
  // recommendStatus: '推荐状态',
  rewardPeo: '打赏设置',
  recover: '恢复',
  rewardInfo: '打赏明细',
  routing: '分账',

  set: '设置',
  save: '新增',
  send: '发布',
  sort: '排序',
  status: '状态',
  section: '部门',
  setLike: '设置猜你想问',
  sortFAQ: '分类管理',
  stockSet: '库存设置',
  shareText: '分享文案',
  sharePush: '发布分享',
  searchSet: '热门搜索配置',
  storeList: '门店列表',
  statistics: '分佣',
  signDetail: '打卡明细',
  setMreCord: '设置商家验证码',
  shareImgAdd: '新增分享图片',
  shareImgEdit: '修改分享图片',
  saveClassify: '添加内容子类',
  savePClassify: '添加内容分类',
  shareTextEdit: '修改分享文案',
  shareImg: '分享图',

  task: '营销卡豆充值',
  topic: '创作设置',
  taskDel: '删除营销卡豆充值',
  taskEnd: '结束营销卡豆充值',
  tradeAdd: '新增类目',
  taskSave: '新增营销卡豆充值',
  taskInfo: '营销卡豆充值任务详情',
  targetSet: '营销卡豆充值设置',
  taskDetail: '营销卡豆充值补贴详情',
  tradeSecondAdd: '添加子类目',
  isDelete: '删除',
  tabEdit: '首页tab配置-编辑',
  tabEditVersion: '首页tab配置-编辑版本',
  tabSaveVersion: '首页tab配置-新增版本',
  tabAddCity: '首页tab配置-新增城市',

  up: '上架',
  user: '用户',
  userOs: '用户端',
  userAdd: '新增用户',
  userEdit: '用户编辑',
  userStatus: '用户状态',
  useInfo: '使用情况',
  UGCVideo_edit: 'UCG视频编辑',
  shareBean_edit: '分享赚豆编辑',
  UGCSave: 'UGC视频标签配置-新增',
  UGCEdit: 'UGC视频标签配置-编辑',
  UGCDown: 'UGC视频标签配置-显示/隐藏',

  videoAd: '视频广告',
  virtualSave: '卡豆抵扣比例配置-新增',
  virtualInfo: '卡豆抵扣比例配置-详情',
  virtualEdit: '卡豆抵扣比例配置-编辑',

  withdraw: '提现记录',
  withdrawGroup: '团长提现',
  withdrawMerchant: '单店卡豆提现',
  withdrawMerchantCash: '单店现金提现',
  withdrawExpert: '哒人提现',
  withdrawAlliance: '加盟商提现',
  weekEdit: '周卡配置编辑',
};

// 数据权限选项
export const WORKER_ROLEDATA_TYPE = [
  { value: 1, name: '本人' },
  { value: 25, name: '本部门（不含下级部门）' },
  { value: 50, name: '本部门及以下级部门 ' },
  { value: 100, name: '全部' },
];
